pipeline modified

diff --git a/.github/workflows/dev-pipeline.yml b/.github/workflows/dev-pipeline.yml
--- a/.github/workflows/dev-pipeline.yml
+++ b/.github/workflows/dev-pipeline.yml
@@ -46,7 +46,7 @@ jobs:
 
       - name: 🚀 Push imagem para Docker Hub
         # Note: Pushing with the 'dev' tag
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/minha-app:dev
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
 
   deploy-to-hetzner:
     name: Deploy na Hetzner
@@ -68,7 +68,7 @@ jobs:
             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
             # Puxa a versão `dev` mais recente
-            docker pull ${{ secrets.DOCKER_USERNAME }}/minha-app:dev
+            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest || { echo "::error::Falha ao enviar a imagem $IMAGE:$TAG"; exit 1; }
 
             # Reinicia o serviço via Docker Compose
             docker compose down
